export const breakfast = [
  {
    id: 0,
    img: "/maggies-chapati.png",
    name: "2 Chapatis",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 1,
    img: "/maggies-mandazi.png",
    name: "3 Mandazis",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 2,
    img: "/maggies-bread.png",
    name: "Bread Portions",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 3,
    img: "/maggies-pancakes.png",
    name: "2 Pancakes",
    category: "Breakfast & Snacks",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 4,
    img: "/maggies-samosa.png",
    name: "3 Pieces Samosa",
    category: "Breakfast & Snacks",
    price: "150",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 5,
    img: "/maggies-omelette.png",
    name: "Omelette 3 Eggs",
    category: "Breakfast & Snacks",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 6,
    img: "/maggies-boiled-eggs.png",
    name: "Fried/Boiled Eggs (2 Pcs)",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 7,
    img: "/maggies-nduma.png",
    name: "Nduma 1pc",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 8,
    img: "/maggies-sweet-potatoes.png",
    name: "Sweet Potatoes",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 9,
    img: "/maggies-maize.png",
    name: "Maize 1 Pc",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 10,
    img: "/maggies-toast.png",
    name: "Toast Mayai",
    category: "Breakfast & Snacks",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 11,
    img: "/maggies-milk-tea.png",
    name: "Milk Tea",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 12,
    img: "/maggies-lemon-tea.png",
    name: "Lemon Tea",
    category: "Breakfast & Snacks",
    price: "150",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 13,
    img: "/maggies-white-coffee.png",
    name: "White Coffee",
    category: "Breakfast & Snacks",
    price: "150",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 14,
    img: "/maggies-black-coffee.png",
    name: "Black Coffee",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 15,
    img: "/maggies-white-chocolate.png",
    name: "White Chocolate",
    category: "Breakfast & Snacks",
    price: "150",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 16,
    img: "/maggies-black-chocolate.png",
    name: "Black Chocolate",
    category: "Breakfast & Snacks",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
];

export const Bitings = [
  {
    id: 1,
    img: "/maggies-sausages.png",
    name: "Sausages 2 Pcs",
    category: "Bitings",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 2,
    img: "/maggies-smokies.png",
    name: "Smokies 2 Pcs",
    category: "Bitings",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 3,
    img: "/maggies-french-fries.png",
    name: "French Fries Plate",
    category: "Bitings",
    price: "150",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 4,
    img: "/maggies-chips-masala.png",
    name: "Chips Masala",
    category: "Bitings",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 5,
    img: "/maggies-solte.png",
    name: "Solte",
    category: "Bitings",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 6,
    img: "/maggies-wedges.png",
    name: "Wedges",
    category: "Bitings",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
];

export const MainCourse = [
  {
    id: 0,
    img: "/maggies-chicken-kienyenji.png",
    name: "Chicken Kienyenji (Dry Fry/Wet Fry)",
    category: "Main Course",
    price: "1500-2000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 1,
    img: "/maggies-chicken-broiler.png",
    name: "Chicken Broiler (Dry Fry/Wet Fry/Deep Fry)",
    category: "Main Course",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 2,
    img: "/maggies-pork.png",
    name: "Pork (Dry Fry/Wet Fry/Choma)",
    category: "Main Course",
    price: "1200 Per Kg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 3,
    img: "/maggies-beef.png",
    name: "Beef (Dry Fry/Wet Fry/Choma)",
    category: "Main Course",
    price: "1200 Per Kg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 4,
    img: "/maggies-goat.png",
    name: "Goat Meet (Dry Fry/Wet Fry/Choma)",
    category: "Main Course",
    price: "1500 Per Kg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 5,
    img: "/maggies-maini.png",
    name: "Maini (Dry Fry/Wet Fry/Choma)",
    category: "Main Course",
    price: "1200 Per Kg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 6,
    img: "/maggies-fish.png",
    name: "Fish (Wet Fry/Dry Fry/Deep Fry)",
    category: "Main Course",
    price: "300-900",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 7,
    img: "/maggies-fried-rice.png",
    name: "Fried Rice",
    category: "Main Course",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 8,
    img: "/maggies-white-rice.png",
    name: "White Rice",
    category: "Main Course",
    price: "150",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 9,
    img: "/maggies-brown-ugali.png",
    name: "Brown Ugali",
    category: "Main Course",
    price: "150",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 10,
    img: "/maggies-white-ugali.png",
    name: "White Ugali",
    category: "Main Course",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 11,
    img: "/maggies-mashed-potatoes.png",
    name: "Mashed Potatoes Portion",
    category: "Main Course",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 12,
    img: "/maggies-managu.png",
    name: "Managu",
    category: "Main Course",
    price: "200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 13,
    img: "/maggies-cabbage.png",
    name: "Cabbage",
    category: "Main Course",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 14,
    img: "/maggies-spinach.png",
    name: "Spinach",
    category: "Main Course",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 15,
    img: "/maggies-sukuma.png",
    name: "Sukuma",
    category: "Main Course",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 16,
    img: "/maggies-dawa.png",
    name: "Dawa",
    category: "Main Course",
    price: "250",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 17,
    img: "/maggies-soup.png",
    name: "Soup",
    category: "Main Course",
    price: "150",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 18,
    img: "/maggies-kachumbari.png",
    name: "Kachumbari",
    category: "Main Course",
    price: "100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
];

export const barMenu = [
  {
    id: 0,
    img: "/drinks-monster.png",
    name: "Monster",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 1,
    img: "/drinks-tusker-can.png",
    name: "Tusker Can",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 2,
    img: "/drinks-tusker-cider.png",
    name: "Tusker Cider",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 3,
    img: "/drinks-pilsner-can.png",
    name: "Pilsner Can",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 4,
    img: "/drinks-white-cap-can.png",
    name: "White Cap Can",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 5,
    img: "/drinks-guiness-can.png",
    name: "Guiness Can",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 6,
    img: "/drinks-pineapple-punch.png",
    name: "Pineapple Punch",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 7,
    img: "/drinks-guarana-can.png",
    name: "Guarana Can",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 8,
    img: "/drinks-black-ice-can.png",
    name: "Blackice Can",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 9,
    img: "/drinks-balozi-can.png",
    name: "Balozi Can",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 10,
    img: "/drinks-gordons-can.png",
    name: "Gordons Can",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 11,
    img: "/drinks-redbull.png",
    name: "Redbull",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 12,
    img: "/drinks-snapp.png",
    name: "Snapp",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 13,
    img: "/drinks-guiness-smooth.png",
    name: "Guiness Smooth",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 14,
    img: "/drinks-king-fisher.png",
    name: "King Fisher",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 15,
    img: "/drinks-tusker-ice.png",
    name: "Tusker Ice",
    category: "Drinks",
    price: "350",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 16,
    img: "/drinks-manyatta-can.png",
    name: "Manyatta Can",
    category: "Drinks",
    price: "350",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 17,
    img: "/drinks-tusker-malt.png",
    name: "Tusker Malt",
    category: "Drinks",
    price: "350",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 18,
    img: "/drinks-savanna.png",
    name: "Savanna",
    category: "Drinks",
    price: "350",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 19,
    img: "/drinks-hunters-dry-gold.png",
    name: "Hunters Dry/Gold",
    category: "Drinks",
    price: "350",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 20,
    img: "/drinks-heineken.png",
    name: "Heineken",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 21,
    img: "/drinks-faxe.png",
    name: "Faxe",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 22,
    img: "/drinks-kc-250ml.png",
    name: "KC 250ml",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 23,
    img: "/drinks-liberty-250ml.png",
    name: "Liberty 250ml",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 24,
    img: "/drinks-cherome-250ml.png",
    name: "Chrome 250ml",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 25,
    img: "/drinks-county-250ml.png",
    name: "County 250ml",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 26,
    img: "/drinks-konyagi-250ml.png",
    name: "Konyagi 250ml",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 27,
    img: "/drinks-best-gin-250ml.png",
    name: "Best Gin 250ml",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 28,
    img: "/drinks-kibao-250ml.png",
    name: "Kibao 250ml",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 29,
    img: "/drinks-just-right-250ml.png",
    name: "Just Right 250ml",
    category: "Drinks",
    price: "400",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 30,
    img: "/drinks-orchid.png",
    name: "Orchid",
    category: "Drinks",
    price: "450",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 31,
    img: "/drinks-delmonte.png",
    name: "Delmonte",
    category: "Drinks",
    price: "450",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 32,
    img: "/drinks-v-a-creame-whisky.png",
    name: "V & A (Creame Whisky)",
    category: "Drinks",
    price: "450",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 33,
    img: "/drinks-captain-morgan-250ml.png",
    name: "Captain Morgan 250ml",
    category: "Drinks",
    price: "500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 34,
    img: "/drinks-best-whisky-250ml.png",
    name: "Best Whisky 250ml",
    category: "Drinks",
    price: "500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 35,
    img: "/drinks-viceroy-250ml.png",
    name: "Viceroy 250ml (Brandy)",
    category: "Drinks",
    price: "600",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 36,
    img: "/drinks-richot-250ml.png",
    name: "Richot 250ml (Brandy)",
    category: "Drinks",
    price: "600",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 37,
    img: "/drinks-gilbeys-250ml.png",
    name: "Gilbeys 250ml (Gin)",
    category: "Drinks",
    price: "600",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 38,
    img: "/drinks-smirnoff-vodka-250ml.png",
    name: "Smirnoff Vodka 250ml",
    category: "Drinks",
    price: "600",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 40,
    img: "/drinks-all-seasons-250ml.png",
    name: "All Seasons 250ml (Whisky)",
    category: "Drinks",
    price: "600",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 41,
    img: "/drinks-bond-7-250ml-whisky.png",
    name: "Bond 7 250ml (Whisky)",
    category: "Drinks",
    price: "600",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 42,
    img: "/drinks-kc-500ml.png",
    name: "KC 500ml",
    category: "Drinks",
    price: "750",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 43,
    img: "/drinks-kibao-500ml.png",
    name: "Kibao 500ml",
    category: "Drinks",
    price: "750",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 44,
    img: "/drinks-konyagi-500ml.png",
    name: "Konyagi 500ml",
    category: "Drinks",
    price: "750",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 45,
    img: "/drinks-hunter-500ml.png",
    name: "Hunter 500ml",
    category: "Drinks",
    price: "750",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 46,
    img: "/drinks-richot-500ml.png",
    name: "Richot 500ml",
    category: "Drinks",
    price: "900",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 47,
    img: "/drinks-viceroy-500ml.png",
    name: "Viceroy 500ml",
    category: "Drinks",
    price: "900",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 48,
    img: "/drinks-black-white-500ml.png",
    name: "Black & White 500ml",
    category: "Drinks",
    price: "900",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 49,
    img: "/drinks-smirnoff-vodka-500ml.png",
    name: "Smirnoff Vodka 500ml",
    category: "Drinks",
    price: "900",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 50,
    img: "/drinks-gilbeys-500ml.png",
    name: "Gilbeys 500ml",
    category: "Drinks",
    price: "900",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 51,
    img: "/drinks-all-seasons-500ml.png",
    name: "All Seasons 500ml",
    category: "Drinks",
    price: "900",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 52,
    img: "/drinks-red-label-500ml.png",
    name: "Red Label 500ml",
    category: "Drinks",
    price: "900",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 53,
    img: "/drinks-vat-69-500ml.png",
    name: "Vat 69 500ml",
    category: "Drinks",
    price: "1100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 54,
    img: "/drinks-bond-7-500ml.png",
    name: "Bond 7 500ml",
    category: "Drinks",
    price: "1100",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 55,
    img: "/drinks-kibao-750ml.png",
    name: "Kibao 750ml",
    category: "Drinks",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 56,
    img: "/drinks-konyagi-750ml.png",
    name: "Konyagi 750ml",
    category: "Drinks",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 57,
    img: "/drinks-kc-750ml.png",
    name: "KC 750ml",
    category: "Drinks",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 58,
    img: "/drinks-county-750ml.png",
    name: "County 750ml",
    category: "Drinks",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 59,
    img: "/drinks-cavibla-750ml.png",
    name: "Cavibla 750ml (Gin)",
    category: "Drinks",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 60,
    img: "/drinks-best-gin-750ml.png",
    name: "Best Gin 750ml",
    category: "Drinks",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 61,
    img: "/drinks-chrome-750ml.png",
    name: "Chrome 750ml",
    category: "Drinks",
    price: "1200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 62,
    img: "/drinks-robertson.png",
    name: "Robertson",
    category: "Wines",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 63,
    img: "/drinks-4th-street.png",
    name: "4th Street",
    category: "Wines",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 64,
    img: "/drinks-4-cousins.png",
    name: "4 Cousins",
    category: "Wines",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 65,
    img: "/drinks-drostdy-hof.png",
    name: "Drostdy Hof",
    category: "Wines",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 66,
    img: "/drinks-3600-south.png",
    name: "3600 South",
    category: "Wines",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 67,
    img: "/drinks-cellar-cast.png",
    name: "Cellar Cast",
    category: "Wines",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 68,
    img: "/drinks-captain-morgan-750ml.png",
    name: "Captain Morgan 750ml",
    category: "Spirit",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 69,
    img: "/drinks-hunters-choice-750ml.png",
    name: "Hunters Choice 750ml",
    category: "Spirit",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 70,
    img: "/drinks-sambuca-750ml.png",
    name: "Sambuca 750ml",
    category: "Spirit",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 71,
    img: "/drinks-best-whiskey-750ml.png",
    name: "Best Whiskey 750ml",
    category: "Spirit",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 72,
    img: "/drinks-gordons-500ml.png",
    name: "Gordon 500ml",
    category: "Spirit",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 73,
    img: "/drinks-douglas-750ml.png",
    name: "Douglas 750ml",
    category: "Spirit",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 74,
    img: "/drinks-william-lawsons-500ml.png",
    name: "William Lawsons 500ml",
    category: "Spirit",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 75,
    img: "/drinks-amarula-500ml.png",
    name: "Amarula 500ml",
    category: "Drinks",
    price: "1800",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 76,
    img: "/drinks-grants-500ml.png",
    name: "Grants 500ml",
    category: "Drinks",
    price: "1800",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 77,
    img: "/drinks-viceroy-750ml.png",
    name: "Viceroy 750ml",
    category: "Drinks",
    price: "2000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 78,
    img: "/drinks-richot-750ml.png",
    name: "Richot 750ml",
    category: "Drinks",
    price: "2000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 79,
    img: "/drinks-black-white-750ml.png",
    name: "Black & White 750ml",
    category: "Drinks",
    price: "2000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 80,
    img: "/drinks-smirnoff-vodka-750ml.png",
    name: "Smirnoff Vodka 750ml",
    category: "Drinks",
    price: "2000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 81,
    img: "/drinks-v-a-750ml.png",
    name: "V & A 750ml",
    category: "Drinks",
    price: "2000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 82,
    img: "/drinks-bond-750ml.png",
    name: "Bond 7 750ml",
    category: "Drinks",
    price: "2000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 83,
    img: "/drinks-black-label-500ml.png",
    name: "Black Label 500ml",
    category: "Drinks",
    price: "2200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 84,
    img: "/drinks-all-seasons-500ml.png",
    name: "All Seasons 500ml",
    category: "Drinks",
    price: "2200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 85,
    img: "/drinks-jameson-500ml.png",
    name: "Jameson 500ml",
    category: "Drinks",
    price: "2200",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 86,
    img: "/drinks-william-lawsons-750ml.png",
    name: "William Lawsons 750ml",
    category: "Drinks",
    price: "2500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 87,
    img: "/drinks-jack-daniels-500ml.png",
    name: "Jack Daniels 500ml",
    category: "Drinks",
    price: "2500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 88,
    img: "/drinks-vat-69-750ml.png",
    name: "V.A.T 69 750ml",
    category: "Drinks",
    price: "2500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 89,
    img: "/drinks-smirnoff-vodka-1l.png",
    name: "Smirnoff Vodka 1L",
    category: "Drinks",
    price: "2500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 90,
    img: "/drinks-baileys-750ml.png",
    name: "Baileys 750ml",
    category: "Drinks",
    price: "3500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 91,
    img: "/drinks-gordons-750ml.png",
    name: "Gordons 750ml",
    category: "Drinks",
    price: "3500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 92,
    img: "/drinks-red-label-750ml.png",
    name: "Red Label 750ml",
    category: "Drinks",
    price: "3500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 93,
    img: "/drinks-ballentimes.png",
    name: "Ballentines",
    category: "Drinks",
    price: "3500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 94,
    img: "/drinks-grants-750ml.png",
    name: "Grants 750ml",
    category: "Drinks",
    price: "3500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 95,
    img: "/drinks-jameson-750ml.png",
    name: "Jameson 750ml",
    category: "Drinks",
    price: "3500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 96,
    img: "/drinks-amarula-750ml.png",
    name: "Amarula 750ml",
    category: "Drinks",
    price: "3500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 97,
    img: "/drinks-jaqermeister-750ml.png",
    name: "Jagermeister 750ml",
    category: "Drinks",
    price: "4000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 98,
    img: "/drinks-amarula-1l.png",
    name: "Amarula 1L",
    category: "Drinks",
    price: "4500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 99,
    img: "/drinks-red-label-1l.png",
    name: "Red Label 1L",
    category: "Drinks",
    price: "4500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 100,
    img: "/drinks-black-label-1l.png",
    name: "Black Label 1L",
    category: "Drinks",
    price: "4500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 101,
    img: "/drinks-tanqueray-750ml.png",
    name: "Tanqueray 750ml",
    category: "Drinks",
    price: "4500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 102,
    img: "/drinks-sevilla-1l.png",
    name: "Sevilla 1L",
    category: "Drinks",
    price: "4500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 103,
    img: "/drinks-grants-1l.png",
    name: "Grants 1L",
    category: "Drinks",
    price: "4500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 104,
    img: "/drinks-gordons-1l.png",
    name: "Gordons 1L",
    category: "Drinks",
    price: "4500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 105,
    img: "/drinks-camino-750ml.png",
    name: "Camino 750ml",
    category: "Drinks",
    price: "4500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 106,
    img: "/drinks-black-label-1l.png",
    name: "Black Label 1L",
    category: "Drinks",
    price: "5500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 107,
    img: "/drinks-jack-jadiels-750ml.png",
    name: "Jack Daniels 750ml",
    category: "Drinks",
    price: "5500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 108,
    img: "/drinks-double-black-750ml.png",
    name: "Double Black 750ml",
    category: "Drinks",
    price: "8000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 109,
    img: "/drinks-martel-vs-750ml.png",
    name: "Martel vs 750ml",
    category: "Drinks",
    price: "8000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 110,
    img: "/drinks-double-black-1l.png",
    name: "Double Black 1L",
    category: "Drinks",
    price: "11000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 111,
    img: "/drinks-martel-vsop.png",
    name: "Martel vsop",
    category: "Drinks",
    price: "15000",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
  {
    id: 112,
    img: "/drinks-all-beers.png",
    name: "All Beers",
    category: "Drinks",
    price: "300",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur assumenda asperiores quas nemo necessitatibus inventore. Quibusdam consequatur sed necessitatibus laudantium nam. Minus doloremque ducimus, porro earum architecto deleniti veniam quas.",
  },
];

export const gallery = [
  {
    id: 0,
    img: "/gallery-1.png",
    alt: "gallery-1",
  },
  {
    id: 1,
    img: "/gallery-2.png",
    alt: "gallery-2",
  },
  {
    id: 2,
    img: "/gallery-3.png",
    alt: "gallery-3",
  },
  {
    id: 3,
    img: "/gallery-4.png",
    alt: "gallery-4",
  },
  {
    id: 4,
    img: "/gallery-5.png",
    alt: "gallery-5",
  },
  {
    id: 5,
    img: "/gallery-6.png",
    alt: "gallery-6",
  },
  {
    id: 6,
    img: "/gallery-7.png",
    alt: "gallery-7",
  },
  {
    id: 7,
    img: "/gallery-8.png",
    alt: "gallery-8",
  },
  {
    id: 8,
    img: "/gallery-9.png",
    alt: "gallery-9",
  },
  {
    id: 9,
    img: "/gallery-10.png",
    alt: "gallery-10",
  },
  {
    id: 10,
    img: "/gallery-11.png",
    alt: "gallery-11",
  },
  {
    id: 11,
    img: "/gallery-12.png",
    alt: "gallery-12",
  },
];
